File <- function(filename, iscen)
{
  cat(file=filename, paste("import functools"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import time"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import numpy as np"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import pandas as pd"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import platform"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import sys"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("if __name__ == \'__main__\':"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("if platform.system() == \"Darwin\":"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("multiprocessing.set_start_method(\'spawn\' ,force=True)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("from trachoma.trachoma_simulations import Trachoma_Simulation"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("def timer(func):"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("@functools.wraps(func)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("def wrapper_timer(*args, **kwargs):"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("print(f\"-> Running {func.__name__!r}\")"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("start_time = time.perf_counter()    # 1"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("value = func(*args, **kwargs)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("end_time = time.perf_counter()      # 2"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("run_time = end_time - start_time    # 3"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("print(f\"=> Finished {func.__name__!r} in {run_time:.4f} secs\\n\\n\")"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("return value"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("return wrapper_timer"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("@timer"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("def test():"), append = T)
  cat(file=filename, "\n", append = T)
  BetFilePath = sprintf('files/InputBet_scen%g.csv', Scen[iscen])
  MDAFilePath = sprintf('files/InputMDA_scen%g.csv', Scen[iscen])
  PrevFilePath = sprintf('output/OutputPrev_scen%g.csv', Scen[iscen])
  InfectFilePath = sprintf('output/InfectFilePath_scen%g.csv', Scen[iscen])
  cat(file=filename, "\t", paste("Trachoma_Simulation(BetFilePath=\'", BetFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("MDAFilePath=\'", MDAFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("PrevFilePath=\'", PrevFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("InfectFilePath=\'", InfectFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("SaveOutput=False,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("OutSimFilePath=None,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("InSimFilePath=None)"), append = T)
}

FilePrev <- function(filename, iscen)
{
  cat(file=filename, paste("import functools"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import time"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import numpy as np"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import pandas as pd"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import platform"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import sys"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("if __name__ == \'__main__\':"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("if platform.system() == \"Darwin\":"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("multiprocessing.set_start_method(\'spawn\' ,force=True)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("from trachoma.trachoma_simulations import Trachoma_Simulation"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("def timer(func):"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("@functools.wraps(func)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("def wrapper_timer(*args, **kwargs):"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("print(f\"-> Running {func.__name__!r}\")"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("start_time = time.perf_counter()    # 1"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("value = func(*args, **kwargs)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("end_time = time.perf_counter()      # 2"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("run_time = end_time - start_time    # 3"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("print(f\"=> Finished {func.__name__!r} in {run_time:.4f} secs\\n\\n\")"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("return value"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("return wrapper_timer"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("@timer"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("def test():"), append = T)
  cat(file=filename, "\n", append = T)
  BetFilePath = sprintf('files/InputBet_scen%g_group%g.csv', Scen[iscen], Group[iscen])
  MDAFilePath = sprintf('files/InputMDA_scen%g.csv', Scen[iscen])
  PrevFilePath = sprintf('output/OutputPrev_scen%g_group%g.csv', Scen[iscen], Group[iscen])
  InfectFilePath = sprintf('output/InfectFilePath_scen%g_group%g.csv', Scen[iscen], Group[iscen])
  cat(file=filename, "\t", paste("Trachoma_Simulation(BetFilePath=\'", BetFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("MDAFilePath=\'", MDAFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("PrevFilePath=\'", PrevFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("InfectFilePath=\'", InfectFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("SaveOutput=False,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("OutSimFilePath=None,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("InSimFilePath=None)"), append = T)
}
